"""TechPilot 共享 Runtime、契约和 Session 持久化。"""

from .bootstrap import ChatRuntime, RuntimeBootstrap, RuntimeBootstrapInput, TaskRuntime
from .contracts import (
    RuntimeMode,
    RuntimeResultScope,
    RuntimeResultStatus,
    TaskRuntimeIdentity,
    TaskRuntimePaths,
    TaskRuntimeResult,
)
from .extensions import (
    RUNTIME_ROLE_API_VERSION,
    ArtifactRequirement,
    EvaluationInterface,
    PayloadContract,
    RoleActivation,
    RoleHostConfiguration,
    RoleRegistration,
    RoleRegistry,
    RoleSkillActivator,
    RoleSpec,
    RuntimeCompatibility,
    SkillPackage,
    SkillRegistry,
    SkillSpec,
    SkillVersion,
    ToolAllowlist,
    ToolRequest,
)

__all__ = [
    "RUNTIME_ROLE_API_VERSION",
    "ArtifactRequirement",
    "ChatRuntime",
    "EvaluationInterface",
    "PayloadContract",
    "RoleActivation",
    "RoleHostConfiguration",
    "RoleRegistration",
    "RoleRegistry",
    "RoleSkillActivator",
    "RoleSpec",
    "RuntimeBootstrap",
    "RuntimeBootstrapInput",
    "RuntimeCompatibility",
    "RuntimeMode",
    "RuntimeResultScope",
    "RuntimeResultStatus",
    "SkillPackage",
    "SkillRegistry",
    "SkillSpec",
    "SkillVersion",
    "TaskRuntime",
    "TaskRuntimeIdentity",
    "TaskRuntimePaths",
    "TaskRuntimeResult",
    "ToolAllowlist",
    "ToolRequest",
]
